[features]
seeds = false



[programs.localnet]
sbvol = "4TtQakHeBgTRjG85RHmWs25LK37DdmfP4PnS45Hmcgd5"


[programs.devnet]
sbvol = "4TtQakHeBgTRjG85RHmWs25LK37DdmfP4PnS45Hmcgd5"


[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/manoj235p/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
